

CREATE SEQUENCE usuarios_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE usuarios(
   id INT GENERATED BY DEFAULT AS SEQUENCE usuarios_id_seq,   
   usuario_twitter VARCHAR(600) UNIQUE,
   siguiendo INT,
   seguidores INT,
   PRIMARY KEY(id)
);


CREATE SEQUENCE tweets_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE tweets(
   id INT GENERATED BY DEFAULT AS SEQUENCE tweets_id_seq,   
   id_usuario INT,
   fecha TIMESTAMP,
   contenido VARCHAR(500),
   likes INT,
   FOREIGN KEY(id_usuario) REFERENCES usuarios,
   PRIMARY KEY(id)
);



CREATE SEQUENCE emociones_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE emociones(
   id INT GENERATED BY DEFAULT AS SEQUENCE emociones_id_seq,   
   id_tweet INT UNIQUE NOT NULL,
   felicidad DOUBLE,
   tristeza DOUBLE,
   enojo DOUBLE,
   miedo DOUBLE,
   animado DOUBLE,  
   indiferente DOUBLE,  
   FOREIGN KEY(id_tweet) REFERENCES tweets,
   PRIMARY KEY(id)
);

CREATE SEQUENCE paises_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE paises(
  id INT GENERATED BY DEFAULT AS SEQUENCE paises_id_seq,   
  codigo VARCHAR(10) UNIQUE,
  nombre VARCHAR(300),
  latitud DOUBLE,
  longitud DOUBLE,
  PRIMARY KEY(id)
);

CREATE SEQUENCE lugares_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE lugares(
   id INT GENERATED BY DEFAULT AS SEQUENCE lugares_id_seq,   
   id_tweet INT UNIQUE,
   latitud DOUBLE,
   longitud DOUBLE,
   id_pais INT,
   FOREIGN KEY(id_tweet) REFERENCES tweets,
   FOREIGN KEY(id_pais) REFERENCES paises,
   PRIMARY KEY(id)
);


CREATE SEQUENCE hashtags_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE hashtags(
   id INT GENERATED BY DEFAULT AS SEQUENCE hashtags_id_seq,   
   nombre VARCHAR(300) UNIQUE,
   PRIMARY KEY(id)
);


CREATE TABLE tweets_hashtags(   
   id_tweet INT,
   id_hashtag INT,   
   FOREIGN KEY(id_tweet) REFERENCES tweets,
   FOREIGN KEY(id_hashtag) REFERENCES hashtags,
   PRIMARY KEY(id_tweet,id_hashtag)
);






/*######## usuarios #######*/
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'KKLC',29,45);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'jvszohjvs',515,477);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'IhwaE',420,427);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'IbpskpUpulz',711,6882);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'wlq',40,18);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'QvbyulfDvthu',4092,43856);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'RHYS',1137,3488);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'vapvzlto',2152,6971);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'qbzapuihjothu',476,2814);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'aylukdopgv',25,249);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Zavrkvn',20,1265);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Dhajothupzmlq',257,451);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'hafwpjhsisvukl',746,463);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'ZhpfhuTfUhtl',117,36);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Mpszvu',983,26521);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Hs',313,16416);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'aqwopnnz',78,86);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'hnpzabmm',165,878);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Zbuypzl',40,63019);
INSERT INTO usuarios(id,usuario_twitter,siguiendo,seguidores) VALUES(DEFAULT,'Zht',584,18857);


/*######## tweets #######*/
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,1,'2020-03-02 20:56:00','The eternal question: @gitlab or @github? Read this deep dive by @codegiantio for the latest technical arguments: https://bit.ly/2RWMb7v  h/t @hackernoon #gitlab #github',6);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,2,'2020-02-02 20:13:42','This guy has been working hard on this modern React canvas library for months. I hate that he only has 26 stars. =/

Go give his repo some love plz!

https://github.com/pinqy520/revas 
#javascript #reactjs #softwaredevelopment #webdevelopment #github #nodejs',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,3,'2020-05-02 17:03:53','Some #GitHub issues are missing from search results, for example https://github.com/anbox/anbox/issues/1097 … does not appear in https://github.com/anbox/anbox/issues?q=ssl …. So Microsoft bought GitHub to do censorship on hacking projects?',1);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,4,'2020-04-02 14:34:45','Free GitHub Satellite Virtual 2020 Event May 6
#GitHub #git #SourceControl #Free #VirtualEvent #DevelopersDevelopersDevelopers #community #software https://build5nines.com/free-github-satellite-virtual-2020-event-may-6/ …pic.twitter.com/EKTuxCmeWu',2);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,5,'2020-04-02 14:15:18','You want to be happy? Set goals, because the amount of Joy, peace and happiness achieved goals brings is immeasurable #programming #Python3 #COVID19Nigeria #github #Nigeria',2);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,6,'2020-05-02 23:55:22','How do you think #airlines should address #social distancing?https://twitter.com/CBSNews/status/1256725036729348097 …',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,7,'2020-05-02 23:44:57','The Philippines is like a no-fly-zone.

#COVID19
#lockdownPhilippines
#quarantine
#aviation
#airlines
#flightssuspension
#coronaviruspic.twitter.com/rRvhPwAGsA',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,8,'2020-05-02 23:43:08','#Covid19 #Airlines #Virgin Belt & Braces by #cathywilcox1 pic.twitter.com/FFBwQcRJ1n #auspol #coronavirus #CovidApp #Insiders',2);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,9,'2020-05-02 23:22:51','Once again, @WarrenBuffett has thrown in the fiscal towel on airline stocks, selling most/all his stakes last month in the largest US carriers as a pandemic vaporized revenues. via @k_chiglinsky #airlines #stocks $AAL $DAL $LUV $UAL',5);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,10,'2020-05-02 23:20:29','yes, seems like #BerkshireHathaway liquidated the stakes in $DAL $AAL $UAL $LUV to raise additional cash. 

At the moment, most of #airlines have negative equity value.

Do we see an #oilprice like #crash of #airlines ? pic.twitter.com/gOdxst1iBX',1);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,11,'2020-05-02 23:58:46','#Mesoblast $MESO $MSB collaborative study in Sydney set to use stem cells to investigate dampening down the excessive immune response and cardio inflammation and improve survival in #COVID patients. https://twitter.com/7NewsAustralia/status/1256708479349186560 …',11);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,12,'2020-05-02 23:58:00','Latest: 
#Christianity Global Report; Iraq #Covid-19, UK Covid, Fulani attack, #Israel, Iran, Laos, from #WarnRadio

Listen on:
#Anchor https://bit.ly/2yetrJJ 
#Blogtalk https://bit.ly/3eYbn7r 
#Spreakerhttp://bit.ly/2PUE4XR ',1);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,13,'2020-05-02 23:57:14','I think #COVID responders would rather have life saving PPE than a 60 second flyover.',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,14,'2020-05-02 23:54:48','#Covid19 #Covid 
President Camacho - The Economy https://youtu.be/3nlvk7qFHTw  via @YouTube',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,15,'2020-05-02 23:52:14','@JennyMikakos @ABCscience @ScottMorrisonMP @JamesMerlinoMP @DanielAndrewsMP @theheraldsun @drkerrynphelps @GregHuntMP @InsidersABC @amapresident am no expert, with cluster of covid at Marist school in NZ -kids with heart damage in UK & Kawasaki like symptoms from #covid  https://twitter.com/lenoretaylor/status/1256351695056957440 …',3);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,16,'2020-05-02 23:59:58','Mother’s Day is coming up so why not give your momma (grandma) some art! DM the photo and draw it for you just $30 pic.twitter.com/KNl16XYhnB',4);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,17,'2020-05-02 23:59:48','hey @scxrlet64 - here are a couple of pics I found of my mother''s necklaces, one beads n stone and a couple of steampunk ones, she does much more, too though. She doesn''t maintain a site, these are just pics I was able to find of old stuff. pic.twitter.com/g6i2QCYN03',0);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,18,'2020-05-02 23:59:48','Mixed-Up Mother Goose, View 76, Loop 4 #spritemap #AGI #Sierrapic.twitter.com/m9uHBnMW0n',1);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,19,'2020-05-02 23:59:47','With Mother’s Day coming up next Sunday we’re giving you the opportunity to make your mum feel special. We’ve teamed up @Optus to keep you connected on Mother’s Day to say G’Day whether near or far. Head to our Facebook page for more info! #gdayadaypic.twitter.com/QsfzIjgSwT',4);
INSERT INTO tweets(id,id_usuario,fecha,contenido,likes) VALUES(DEFAULT,20,'2020-05-02 23:59:41','The Fed''s ran on a platform of reducing poverty 5 years now they have done nothing for social assistance sole exception they have helped out in 5 years has been low income mother''s that''s great but adults have been fucked over by the Fed''s and the provinces disabled need help now',1);

/*######## hashtags #######*/
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'gitlab');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'github');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'softwaredevelopment');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'javascript');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'webdevelopment');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'nodejs');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'reactjs');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'git');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'software');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'free');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'virtualevent');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'sourcecontrol');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'community');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'developersdevelopersdevelopers');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'covid19nigeria');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'python3');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'programming');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'nigeria');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'airlines');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'social');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'flightssuspension');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'quarantine');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'aviation');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'lockdownphilippines');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'coronaviruspic');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'covid19');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'coronavirus');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'cathywilcox1');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'virgin');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'auspol');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'covidapp');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'insiders');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'stocks');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'crash');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'berkshirehathaway');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'oilprice');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'mesoblast');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'covid');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'anchor');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'warnradio');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'spreakerhttp');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'blogtalk');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'christianity');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'israel');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'sierrapic');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'agi');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'spritemap');
INSERT INTO hashtags(id,nombre) VALUES(DEFAULT,'gdayadaypic');

/*######## tweets_hashtags #######*/
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(1,1);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(1,2);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,3);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,4);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,5);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,2);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,6);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(2,7);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(3,2);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,8);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,9);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,10);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,11);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,12);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,13);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,2);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(4,14);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(5,15);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(5,2);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(5,16);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(5,17);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(5,18);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(6,19);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(6,20);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,21);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,19);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,22);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,23);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,24);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,25);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(7,26);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,26);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,19);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,27);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,28);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,29);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,30);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,31);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(8,32);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(9,19);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(9,33);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(10,34);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(10,19);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(10,35);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(10,36);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(11,37);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(11,38);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,39);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,40);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,41);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,42);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,43);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,38);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(12,44);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(13,38);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(14,26);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(14,38);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(15,38);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(18,45);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(18,46);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(18,47);
INSERT INTO tweets_hashtags(id_tweet,id_hashtag) VALUES(19,48);

/*######## pais #######*/
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'HUN','Magyarország', 47.49814, 19.04055);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'USA','United States',38.89206,-77.01991);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'FRA','France',48.85689,2.3508);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'AUS','Australia',-36.84813, 144.30035);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'CAN','Canada',45.42042, -75.69243);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'ZAF','South Africa',-25.74602, 28.18712);
INSERT INTO paises(id,codigo,nombre,latitud,longitud) VALUES(DEFAULT,'NLD','Netherlands',52.37317, 4.89066);

/*######## lugares #######*/
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,1,46.82334,17.62002,1);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,2,29.38402,-94.90255,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,3,48.94125,2.57802,3);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,4,28.24889,-81.28012,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,5,-36.84813,144.30035,4);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,6,45.42042,-75.69243,5);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,7,37.87363,-122.45576,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,8,-35.28078,149.1314,4);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,9,29.38402,-94.90255,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,10,40.71305,-74.00723,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,11,-36.84813,144.30035,4);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,12,35.46398,-97.38855,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,13,-34.06036,18.65124,6);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,14,40.62298,-79.15603,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,15,47.60323,-122.33028,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,16,37.78008,-122.42016,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,17,37.78008,-122.42016,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,18,52.37317,4.89066,7);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,19,40.71305,-74.00723,2);
INSERT INTO lugares(id,id_tweet,latitud,longitud,id_pais) VALUES(DEFAULT,20,37.78008,-122.42016,2);



/*######## emociones #######*/
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,1,4e-06,4e-06,2e-06,6e-06,0.999982,2e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,2,2e-06,6e-06,0.999954,9e-06,5e-06,2.3e-05);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,3,9e-06,2.2e-05,0.999841,3.6e-05,1.3e-05,8e-05);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,4,9e-06,4e-06,1e-06,3e-06,0.999981,2e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,5,5.7e-05,4e-06,3e-06,3e-06,0.99993,2e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,6,1.7e-05,1.1e-05,2.2e-05,8e-06,1.3e-05,0.999929);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,7,0.001843,0.004346,0.949013,0.005598,0.002354,0.036847);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,8,1.2e-05,4e-06,8e-06,2e-06,1e-05,0.999964);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,9,6e-06,1e-05,0.999762,2.6e-05,1.4e-05,0.000182);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,10,0.010375,0.046332,0.395707,0.032189,0.013824,0.501573);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,11,0.001314,0.024451,3.4e-05,0.936127,0.03518,0.002894);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,12,0.999635,2.8e-05,1.6e-05,1.1e-05,0.000306,4e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,13,6e-06,1.2e-05,0.999884,2.6e-05,1.1e-05,6.1e-05);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,14,1.1e-05,3e-06,9e-06,2e-06,9e-06,0.999966);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,15,4e-06,0.000259,9e-06,0.999723,4e-06,2e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,16,0.999953,5e-06,2e-06,7e-06,2.8e-05,5e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,17,0.233674,0.000171,8e-06,0.76293,0.003194,2.2e-05);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,18,8.4e-05,9e-06,6e-06,7e-06,0.999893,1e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,19,0.999964,5e-06,2e-06,7e-06,1.7e-05,5e-06);
INSERT INTO emociones(id,id_tweet,felicidad,tristeza,enojo,miedo,animado,indiferente) VALUES(DEFAULT,20,2e-06,4e-06,0.999962,7e-06,5e-06,2e-05);
